name: Inspirata
favicon: null
layout_spectrum: 0.21533459541387856
typography_spectrum: 0.6163933763746172
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#06070c'
    - '#e1c193'
    - '#746779'
    - '#708ebc'
    - '#de936c'
  brandStrength: 0.368714451091364
  lightness: 0.07179611152969301
  saturation: 0.3125
  rhythmicContrast: 0.837446725461632
purpose: []
