name: Inspirata
favicon: null
layout_spectrum: 0.21533459541387856
typography_spectrum: 0.6163933763746172
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6a6873'
    - '#0e0c0d'
    - '#2e2c2f'
    - '#92807e'
    - '#564a4c'
  brandStrength: 0.75
  lightness: 0.07179611152969301
  saturation: 0.3125
  rhythmicContrast: 0.837446725461632
purpose: []
